- README.md
- docs/contribute.md
- docs/datasets.md
- graphium/data/datamodule.py
- graphium/data/utils.py
- graphium/trainer/losses.py
- pyproject.toml
- tests/test_data_utils.py
> Fix unittests

- README.md
- env.yml
- pyproject.toml
- requirements_ipu.txt
Fixes IPU installation instructions
> fix IPU install instructions

- graphium/data/collate.py
- graphium/data/datamodule.py
- graphium/data/dataset.py
- tests/test_collate.py
- Track dtypes of labels to prevent dtype mismatch error on IPU
---
_Checklist:_
---
> Fix label dtype error

- docs/tutorials/gnn/add_new_gnn_layers.ipynb
- docs/tutorials/gnn/making_gnn_networks.ipynb
- docs/tutorials/gnn/using_gnn_layers.ipynb
@DomInvivo I updated the GNN tutorials.
> Reworking GNN tutorials

- .gitignore
- README.md
> Removed note from the readme

- lightning.txt
> add lightning.txt file

- docs/tutorials/model_training/running-multitask-ipu.ipynb
This is hosted on the Graphcore paper space repository as well, the links will take users to paper space. 
But seems like a good idea to have this in the Graphium repository as well. 
---
_Checklist:_
---
> Adding the IPU notebook to the graphium repo as well

- env.yml
- graphium/features/properties.py
- graphium/trainer/predictor_summaries.py
- pyproject.toml
- requirements_ipu.txt
- Remove the `mordred` dependencies. It is unused and `mordred` is also unmaintained for a while and not compatible anymore with the latest versions of NumPy.
- Cleanup the env.yml file to clearly separate optional from mandatory dependencies.
---
_Checklist:_
---
@DomInvivo for context we have removed `mordred` from `molfeat` as well.
> Clean dependencies and remove mordred deps

- docs/_assets/css/custom-graphium.css
- docs/_assets/css/custom.css
- docs/_assets/js/google-analytics.js
- mkdocs.yml
- Add Google Analytics support
- Fix small typo and little tweaks
---
_Checklist:_
---
> add google analytics support and little tweaks

- graphium/data/datamodule.py
- graphium/data/dataset.py
> Fixed OGB test. Added black

- .github/workflows/test.yml
- env.yml
- Enable pytorch 2 in CI
---
_Checklist:_
---
> Enable pytorch 2 in CI

- .github/workflows/test_ipu.yml
- tests/test_ipu_dataloader.py
- tests/test_ipu_to_dense_batch.py
Something causes these tests to hang on the GitHub action but not locally. It doesn't seem super consistent as to which tests cause which processes to break to step though to work it out. 
---
> [TEMP] Fix to the CI - all tests passing

- graphium/config/_loader.py
- Minor fix to allow strategy setting.
> Strategy defaults to 'auto'

- README.md
- enable_ipu.sh
- install_ipu.sh
- Introduced `install_ipu.sh`:
- create a new virtual environment
- download and install Poplar SDK
- pip install requirements
- download toymix datasets and splits
- Introduced `enable_ipu.sh`:
- enable both SDK and venv
- Modified the ipu installation bits in the readme
> Simple ipu install

- docs/baseline.md
- Fixed the CE or BCE to CE or MSE in the `baselines.md`
---
_Checklist:_
---
> Fixed the CE or BCE to CE or MSE

- graphium/ipu/ipu_wrapper.py
- graphium/trainer/predictor.py
- Add `dataloader_idx` argument to pytorch lightning callbacks to fix errors when using certain pytorch lightning versions.
---
_Checklist:_
---
> Add dataloader_idx argument to callbacks

- docs/datasets.md
- update dataset links in the documentation
> update dataset links

- expts/hydra-configs/tasks/loss_metrics_datamodule/admet.yaml
- graphium/cli/train_finetune_test.py
- graphium/nn/architectures/encoder_manager.py
- graphium/nn/architectures/global_architectures.py
- graphium/nn/encoders/laplace_pos_encoder.py
- graphium/nn/pyg_layers/gps_pyg.py
- graphium/nn/pyg_layers/mpnn_pyg.py
- graphium/utils/spaces.py
- Add `eval` resolver for OmegaConf for more scriptable configuration
- Fix pe_encoders that are neither `feat` nor `edge_feat`
- Add `out_dim_edges` for gnn network (previously it was forced to be the same as last `hidden_dims_edges`)
- Fix multiaggregation for mpnn when passing multiple aggregation methods
- Added a few non-ipu losses that had corresponding ipu function.
---
_Checklist:_
---
> Minor fixes

- .gitignore
- graphium/cli/train_finetune_test.py
- graphium/config/_loader.py
- graphium/nn/utils.py
- graphium/trainer/predictor.py
- graphium/trainer/predictor_options.py
- scripts/scale_mpnn.sh
- Fixed few bugs in mup implementation and added sample script for mup scaling `bash scripts/scale_mpnn.sh`
- Included option to resume traning via graphium-train `--config-path=[path to cfg] --config-name=[cfg name] +trainer.resume_from_checkpoint=[location of checkpoint] `
Some explanation on the remaining arguments in `scripts/scale_mpnn.sh`:
- Add scaling factor of model width `+architecture.mup_scale_factor=2 
- Provide base shapes from base model `+architecture.mup_base_path=mup/mpnn_base/base_shapes.yaml` (can be found at files produced by `wandb`)
- When necessary, use gradient accumulation and scale `batch_size` with the inverse to retain same effective batch size `datamodule.args.batch_size_inference=1024 datamodule.args.batch_size_training=1024 …
> Few mup updates

- graphium/cli/train_finetune_test.py
- graphium/config/_loader.py
- Artifact in W&B no longer contain all *.yaml and *.pickle from your CWD.
- Additionally unresolved config is being logged as an artifact.
---
_Checklist:_
---
> Fix artifact logging, log unresolved config

- graphium/nn/pyg_layers/gps_pyg.py
> Trialpushbranch

- graphium/data/datamodule.py
- tests/test_datamodule.py
- Fixed old docs in `datamodule.py`
- Added support for indices passed as a Dict.
---
> Fixed docs in datamodule. Added support for dict indices.

- README.md
- docs/cli/graphium-train.md
- Updating the `## Running an experiment` section in the Readme
---
_Checklist:_
---
> Updated readme `graphium-train` to newer version

- README.md
removed Gradient notebook link from README
---
_Checklist:_
---
> removed Gradient notebook link from README

- graphium/utils/read_file.py
- mkdocs.yml
- tests/test_utils.py
There was an import that was failed to be removed. See PR #513
> Revert "fix: Remove compromised link to polyfill.io"

- graphium/graphium_cpp/commute.cpp
- graphium/graphium_cpp/commute.h
- graphium/graphium_cpp/electrostatic.cpp
- graphium/graphium_cpp/electrostatic.h
- graphium/graphium_cpp/features.cpp
- graphium/graphium_cpp/features.h
- graphium/graphium_cpp/float_features.cpp
- graphium/graphium_cpp/float_features.h
- graphium/graphium_cpp/graphium_cpp.cpp
- graphium/graphium_cpp/graphormer.cpp
- graphium/graphium_cpp/graphormer.h
- graphium/graphium_cpp/labels.cpp
- graphium/graphium_cpp/labels.h
- graphium/graphium_cpp/one_hot.cpp
- graphium/graphium_cpp/one_hot.h
- graphium/graphium_cpp/random_walk.cpp
- graphium/graphium_cpp/random_walk.h
- graphium/graphium_cpp/spectral.cpp
- graphium/graphium_cpp/spectral.h
- Added C++ file description comments
---
_Checklist:_
---
> Added C++ file description comments
