datamol-io/graphium

- graphium/ipu/ipu_utils.py
Making this change because the original PopTorch error has better information about how to resolve the issue.
- Raise upstream PopTorch error if `import poptorch` fails
---
_Checklist:_
---
> Raise original error if `poptorch` cannot be imported

- env.yml
- Pin `pydantic` to `<2` cuz of `lightning`. See https://github.com/Lightning-AI/lightning/pull/18022 and https://github.com/Lightning-AI/lightning/issues/18026. 
---
_Checklist:_
---
> Pin `pydantic` to `<2` cuz of `lightning`

- graphium/config/_loader.py
- Trying to use accelerator hardware when it is not available now issues an error instead of a warning. This prevents situations where accelerator-specific options are used but unavailable, causing non-obvious errors to occur.
---
_Checklist:_
---
> Fail if hardware not available

- expts/configs/config_tdc_admet_demo.yaml
- graphium/data/__init__.py
- graphium/data/datamodule.py
- graphium/data/dataset.py
- graphium/utils/spaces.py
- notebooks/finetuning-on-tdc-admet-benchmark.ipynb
- tests/test_multitask_datamodule.py
- Added `ADMETBenchmarkDataModule`. This new data-module allows you to access any of the benchmarks in the TDC [ADMET benchmark group](https://tdcommons.ai/benchmark/admet_group/overview/).
- Spotted and fixed an issue where splits saved to a Pandas DataFrame were truncated.
- Spotted and fixed an issue issue where the indices in the split could be wrongly specified. 
---
_Checklist:_
---
- I implemented `ADMETBenchmarkDataModule` as a light subclass of `MultitaskFromSmilesDataModule`, similar to `GraphOGBDataModule`. 
- I only added the ADMET benchmark group. There is other benchmarks and other datasets in TDC, but these do not seem relevant to Graphium as of now.
- I decided to rely on [`PyTDC`](https://pypi.org/project/PyTDC/) as an optional dependency (instead of e.g. downloading the …
> Made the TDC ADMET Benchmark group available in Graphium

- graphium/nn/architectures/global_architectures.py
I've stumbled on this error and found it very cryptic. The error message is the same for inconsistent node or edge dimensions which makes it worse. I've added references to `pre-NN` and `pre-NN-edges` and include the inconsistent values in the error message. Hopefully this makes it easier for the user to understand what is wrong in the config.
> improve inconsistent dimensions error messages

- expts/neurips2023_configs/debug/config_large_gcn_debug.yaml
- expts/neurips2023_configs/debug/config_small_gcn_debug.yaml
- graphium/config/_loader.py
- graphium/ipu/ipu_utils.py
With Lightning 2.0, `precision: 16` means mixed precision (activations are computed in fp16 but weight update is done in fp32). For the IPU we want to train in true 16 precision, which Lightning represents as "16-true".
Also, precision needs to be passed to the function that sets IPUOptions, in order to set half-partials.
I've only corrected the precision in the debug configs. More configs should be fixed.
> Using 16-true precision

- graphium/data/datamodule.py
There was a change introduced in commit c43cb26, to drop NaNs from spits files. However this assumes that splits files are represented as Pandas DataFrames. This is not always the case, and the code breaks when the data is represented in lists.
This PR introduces a way to filter NaNs from splits file that is compatible with both lists and pandas DataFrames.
> filter splits NaNs

- expts/neurips2023_configs/base_config/large.yaml
- expts/neurips2023_configs/debug/config_large_gcn_debug.yaml
- graphium/trainer/predictor_summaries.py
> Metric fix: auroc avpr and metric averaging

- graphium/nn/architectures/global_architectures.py
- graphium/nn/pyg_layers/gated_gcn_pyg.py
- Added an `eps` parameter to the `GatedGCNPyg` layer, with a default value of `1e-3` since `1e-6` was causing numerical issues in float16.
- Removed some useless lines of code from the `FullGraphMultiTaskNetwork.forward`
---
_Checklist:_
---
> Fixed GatedGCN in float16. Minor cleanups.

- graphium/trainer/predictor.py
- graphium/trainer/predictor_summaries.py
- graphium/utils/tensor.py
- tests/test_utils.py
- Casting the tensors to float32 before computing the metrics. This prevents overflowing when there are a lot of samples.
- Changed `predictions` to `preds`
- Added functions `tensor_fp16_to_fp32` and `dict_tensor_fp16_to_fp32` with their unit-tests
---
_Checklist:_
---
@luis-mueller can you double-check that the metrics now work without overflow?
> Gpu mixed-precision overflow fix

- .github/workflows/test.yml
- graphium/finetuning/finetuning_architecture.py
- Fixes #439 by changing an `isinstance` check that uses Python syntax that was not supported before Python 3.10.
- Expanded the tests to also run on Python 3.8 and 3.9, so that we catch issues like these fast and early next time. 
---
_Checklist:_
> Fix isinstance check and broadened tests to include more Python versions

- graphium/config/_loader.py
- Fix `trainer.trainer.strategy`. Previously the argument was passed twice for `Trainer` construction and thus error.
---
_Checklist:_
---
> Fix `strategy` argument for trainer

- graphium/data/datamodule.py
- Expose `multiprocessing_context` argument for DataModule classes (constructor & config).
---
_Checklist:_
---
Changing `multiprocessing_context` to `spawn` can sometimes give a significant data loading speedup.
> Expose multiprocessing_context for dataloading

- graphium/data/multilevel_utils.py
- graphium/data/utils.py
- tests/test_multitask_datamodule.py
- The previous code was allowing inconsistent number of labels per molecule to go through, leading to errors if there are mistakes in the dataset or the choice of `label_cols`. For instance, if we have the cols `node_feat1` of size 10, and `node_feat2` of size 12, but they're both for the same molecule, then the code should either crash, or filter out the inconsistencies.
@engmubarak48 and @luis-mueller , I'm not sure I understand all the logic implemented for the padding, so I'd like your opinion on this PR.
---
_Checklist:_
---
> Node inconsistent hydrogens number

- graphium/trainer/predictor.py
- pyproject.toml
- Properly define the `graphium-train` CLI command in the `pyproject.toml`. 
- Revert the changes on calling the `setup()` only for relevant changes.
> Fixed the CLI command definition and data module preparation

- graphium/cli/train_finetune_test.py
- graphium/trainer/predictor.py
- Fix wandb support when using distributed training (`torchrun`)
- sync metrics across distributed training processes.
---
_Checklist:_
---
> Fix distributed training artifact and metrics logging

- graphium/cli/train_finetune_test.py
- Account for `deviceIterations` in logging of `samples_seen`
---
_Checklist:_
---
> Fix `samples_seen` logging

- graphium/cli/train_finetune_test.py
- graphium/nn/pyg_layers/mpnn_pyg.py
- Avoid removing `dirpath` from config as used for saving checkpoint to `wandb`
- Setting `mlp_expansion_ration` from 4 back to 2
---
_Checklist:_
---
> Reverting few changes

- graphium/nn/architectures/__init__.py
- graphium/nn/architectures/global_architectures.py
- graphium/nn/base_layers.py
- graphium/nn/ensemble_layers.py
- graphium/utils/spaces.py
- tests/test_ensemble_layers.py
The goal is to enable an ensemble of MLP's that are trained simultaneously, and where the linear operations are parallelized. This could prove useful (or not) for fine-tuning since we observe large discrepancies between various runs on small datasets.
Features added
These do not allow true Ensembles, as they are averaged together before computing the loss. In ensembles, each model should have it's own loss. This could be implemented in `MetricWrapper`
---
_Checklist:_
---
> EnsembleMLP and EnsembleFeedForwardNN to enable parallelization of ensemble models

- env.yml
- graphium/nn/architectures/global_architectures.py
- graphium/nn/pyg_layers/gps_pyg.py
- Added `embed_dim` to the list of keys to look for when doing the mup kwargs
@maciej-sypetkowski I think this should fix your issue, although I can't verify it because on my end, when I use the config with `architecture.mup_scale_factor: 2` it works. Basically, I can't reproduce because I don't know how you do your scaling for it to fail, but at least the `attn_layer` keys in `mup_base_params.yaml` are no longer `null`.
when this PR closes, it will affect the reproducibility of your models if they use `AttentionLayerMup`, such as `GPSLayerPyg` since the mup will affect the learning rate of these layers, whether they were previously ignored.
> Fix mup for the layers with AttentionLayerMup

- graphium/data/smiles_transform.py
- graphium/features/featurizer.py
- graphium/features/properties.py
- profiling/profile_mol_to_graph.py
A major bug was discovered when working with node, nodepair and edge-level tasks. 
The bug is due to RDKIT's weird behaviour in that it takes the AtomMapping and displays them correctly, but doesn't use them as indices. Unless you specify that you want to canonicalize the molecule. In case you have AtomMaps defined, it will NOT search for a canonical form, instead it will use the AtomMaps.
Below is the weird behaviour by RDKIT, the big numbers next to the carbons are the AtomMapping that are used to order the atoms with the same ordering as the labels. The small numbers are the indices. When visualizing the molecules to validate that the code was working, I didn't not look at the intrinsic indices, but only at the big number, assuming that the indices were correct.
**I'm sorry for the …
> MAJOR-BUG for node/edge predictions: Added ordered=True to `to_mol`

- README.md
> remove Gradient links in README

- env.yml
- Pinning version of `numpy` to the latest version < 2.0. `graphium` uses the old `numpy` API and must be below version 2.0 for now.
- Unpinning the version for the `cuda-version` package. This allows for the CUDA-compatible version of `pytorch` to be installed
- Pinning the version of `rdkit` to a recent version which contains all of the required files (imports) for `graphium_cpp`
---
_Checklist:_
---
> Updating dep versions for bh2 install
